### ISSUE TITLE
Figuring out how we can use Firebase

### ISSUE THREAD

**Issue by JulesssG** [nheyek/SDP-2018#85]
- Setup a Firebase db
- Documentating the workflow
- Testing

FIrst hardcode an user within the app.

**Comment by Amustache** [comment]
Firebase is used to manage the backend of an app.
It is the database part that is interesting for us, but there is a lot of other functionnalities that could be used.

**Comment by Amustache** [comment]
https://firebase.google.com/docs/android/setup?authuser=0

**Comment by Amustache** [comment]
We will use the Firebase authentification service to use the token received from tequila with each request to the server so that a malicious user can't impersonate somebody else.
