### ISSUE TITLE
Add use of API of tequila to login

### ISSUE THREAD

**Issue by Gorzen** [nheyek/SDP-2018#9]

**Comment by Amustache** [comment]
Sorry for the lack of update.
So far:
- Studied the "big picture" of the API
- Tried to make a server work
- Tried to setup a Java client
- Sent mail to the EPFL for them to grant access to their servers

**Comment by Amustache** [comment]
Update:
- Reading a lot of documentation
- Tried to make the thing work
- Contacted about half a dozen people, no one seems to have a clue of what to do
- Finally got the information that we have to rely of one of the people previously contacted (mh)
